workflows:
  ios-build:
    name: Flutter iOS Simulator Build
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      flutter: stable
      xcode: latest

    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods

    scripts:
      - name: Flutter Clean Install
        script: |
          flutter clean
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          flutter pub get

      - name: Pod Install Fresh
        script: |
          cd ios
          pod deintegrate
          pod install --repo-update
          cd ..

      - name: Build iOS Simulator (NO SIGNING)
        script: |
          flutter build ios --debug --simulator --no-codesign

    artifacts:
      - build/ios/iphonesimulator/*.app
