workflows:
  ios-build:
    name: Flutter iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Flutter Setup
        script: |
          flutter clean
          flutter pub get

      - name: Pod Reset
        script: |
          cd ios
          rm -rf Pods
          rm -rf Podfile.lock
          pod deintegrate
          pod install --repo-update
          cd ..

      - name: iOS Simulator Build (NO SIGN)
        script: |
          flutter build ios --simulator --debug

    artifacts:
      - build/ios/iphonesimulator/*.app
