workflows:
  ios-build:
    name: iOS Simulator NO SIGN Build
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Flutter Setup
        script: |
          flutter clean
          flutter pub get

      - name: Build iOS Simulator ONLY
        script: |
          flutter build ios --simulator --debug --no-codesign

    artifacts:
      - build/ios/iphonesimulator/*.app
