# Flutter yardımcı scriptini yükle
load File.join(File.dirname(File.realpath(__FILE__)), 'Flutter', 'podhelper.rb')

platform :ios, '13.0' # ARKit için en az 13.0 şart

target 'Runner' do
  use_frameworks!
  use_native_modules!

  # Flutter paketlerini bağla
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      flutter_additional_ios_build_settings(target)
      
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
          '$(inherited)',
          # PERMISSION_HANDLER İZİNLERİ
          'PERMISSION_CAMERA=1',
          'PERMISSION_MICROPHONE=1',
          'PERMISSION_PHOTOS=1',
        ]
      end
    end
  end
end